export const projectsData = [
  {
    id: 1,
    slug: 'sovereign-sre',
    title: 'Sovereign SRE',
    tagline: 'Detect → Diagnose → Fix → Deploy — all without paging anyone.',
    description: 'Production-grade autonomous SRE platform on 13 AWS services. CloudWatch alarms trigger a LangGraph + CrewAI multi-agent pipeline that diagnoses incidents with codebase-aware RAG (pgvector), generates patches via Amazon Bedrock, and deploys only after human approval via Step Functions + SNS. Live on AWS Amplify.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/Sovereign-SRE',
    demo: 'https://main.d2qpjzu9cicpu8.amplifyapp.com/',
    category: 'ai',
    categoryLabel: 'AI / LLM',
    catIcon: 'fas fa-brain',
    metric: '13 AWS Services',
    tags: ['LangGraph', 'Amazon Bedrock', 'AWS', 'CrewAI'],
    background:
      "Production systems fail in unpredictable ways. Traditional SRE relies on human engineers on-call, following runbooks, and debugging under extreme pressure — an expensive, error-prone process at scale. Sovereign SRE closes this loop autonomously: CloudWatch alarms route through EventBridge and Lambda into a LangGraph state machine, where CrewAI agents diagnose the incident using codebase embeddings stored in RDS pgvector, then Bedrock Claude Haiku generates a targeted code patch. The entire pipeline is orchestrated by Step Functions, which pauses for a mandatory human approval via SNS email before any fix is deployed. Every incident is fully auditable — diffs in S3, history in DynamoDB, cost metrics in CloudWatch.",
    workflow: [
      {
        title: 'Alarm Ingestion',
        text: 'CloudWatch monitors logs and custom metrics. ERROR/CRITICAL severity events trigger an alarm that routes through EventBridge to a Lambda handler, which initiates the Step Functions execution.',
      },
      {
        title: 'Step Functions Orchestration',
        text: 'AWS Step Functions coordinates the full healing pipeline using a waitForTaskToken pattern — the workflow pauses at the approval gate and resumes only when the engineer responds via the SNS email link.',
      },
      {
        title: 'Multi-Agent Root Cause Analysis',
        text: 'LangGraph runs a typed state machine through CrewAI agents: a Senior SRE agent diagnoses the incident and a System Researcher agent queries the codebase via LlamaIndex RAG backed by RDS pgvector embeddings.',
      },
      {
        title: 'Bedrock Patch Generation',
        text: 'Amazon Bedrock (Claude Haiku) generates a targeted code patch with a diff preview. Groq Llama 3.3 serves as a fallback LLM. GitHub integration automatically opens a PR with the proposed fix.',
      },
      {
        title: 'Human Approval Gate',
        text: 'The engineer receives an SNS email with approve/reject links (1-hour expiry). On approval, Step Functions resumes and the fix is deployed. All outcomes are logged to DynamoDB and artifacts stored in S3.',
      },
    ],
    results: [
      'Full incident-to-fix pipeline runs on 13 AWS services across compute, storage, messaging, and AI inference',
      'Step Functions waitForTaskToken pattern ensures no autonomous deployment without engineer sign-off',
      'RDS pgvector RAG retrieves codebase context for accurate, targeted patch generation',
      '31 passing tests with full AWS service mocking via moto — CI-ready from day one',
      'Live deployment: dashboard on AWS Amplify, API on EC2, vector DB on RDS (us-east-2)',
    ],
    highlights: [
      '13 AWS services: CloudWatch Logs/Alarms/Metrics, EventBridge, Lambda, Step Functions, SNS, Bedrock, RDS pgvector, DynamoDB, S3, SSM, EC2',
      'LangGraph state machine with CrewAI Senior SRE + System Researcher agents',
      'Amazon Bedrock (Claude Haiku) for patch generation; Groq Llama 3.3 fallback',
      'Step Functions waitForTaskToken human approval gate — no autonomous deploys',
      'Real-time Next.js dashboard with WebSocket agent streaming',
      'GitHub API integration for automatic PR creation with diff previews',
    ],
    techStack: [
      { label: 'AWS', items: ['CloudWatch', 'Step Functions', 'Lambda', 'Bedrock', 'RDS pgvector', 'DynamoDB', 'S3', 'SNS'] },
      { label: 'AI Agents', items: ['LangGraph', 'CrewAI', 'LlamaIndex'] },
      { label: 'Inference', items: ['Amazon Bedrock', 'Claude Haiku', 'Groq Llama 3.3'] },
      { label: 'Backend / Frontend', items: ['FastAPI', 'WebSockets', 'Next.js 15', 'React 19'] },
    ],
  },
  {
    id: 2,
    slug: 'llm-eval-harness',
    title: 'LLM Eval Harness',
    tagline: 'Benchmark any LLM across latency, accuracy, hallucination, and cost — in one automated pipeline.',
    description: 'Production-grade benchmarking framework that evaluates OpenAI, Anthropic, and Groq models simultaneously across latency (p50/p95/p99, TTFT), accuracy (semantic similarity, LLM-as-judge), hallucination (NLI cross-encoder), cost, and RAGAS metrics — with Rich terminal output, self-contained HTML reports, and a Streamlit comparison dashboard.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/llm-eval-harness',
    category: 'ai',
    categoryLabel: 'AI / LLM',
    catIcon: 'fas fa-brain',
    metric: '6 Models · 5 Metrics',
    tags: ['LLM Benchmarking', 'RAGAS', 'Streamlit', 'Async'],
    background:
      "Choosing an LLM for production is not just about accuracy — it's a multi-dimensional trade-off between latency, hallucination risk, and cost. Most evaluations are ad hoc: a few prompts, subjective scoring, no reproducibility. LLM Eval Harness replaces that with a fully automated, configurable pipeline that evaluates any combination of OpenAI, Anthropic, and Groq models in parallel against a structured JSONL dataset. The key architectural insight is that each evaluation dimension (latency, quality, hallucination, cost) requires a different measurement strategy — and fusing them into a single comparable report is what makes the framework useful for real deployment decisions. The NLI-based hallucination detector (deberta-v3-small cross-encoder) and RAGAS suite provide grounded, reproducible quality signals far beyond simple accuracy metrics.",
    workflow: [
      {
        title: 'Dataset Ingestion',
        text: 'A JSONL dataset of Q&A pairs (with id, question, ground_truth, context, and metadata fields) is loaded by the CLI entrypoint. The context field supports RAG-style evaluation where hallucination detection is grounded against retrieved passages.',
      },
      {
        title: 'Parallel Model Runners',
        text: 'asyncio-based runners for OpenAI (gpt-4o, gpt-4o-mini), Anthropic (claude-sonnet, claude-haiku), and Groq (llama-3.3-70b, llama-3.1-8b) execute concurrently with a configurable concurrency limit (default: 5). Each runner implements a shared BaseRunner interface, making new providers trivial to add.',
      },
      {
        title: 'Metrics Engine',
        text: 'After each model response is collected, the metrics engine computes five dimensions: (1) Latency — p50/p95/p99 percentiles, TTFT, and tokens/sec; (2) Accuracy — exact match and semantic similarity via sentence-transformers; (3) LLM-as-Judge — a secondary model scores responses 1–5 for quality; (4) Hallucination — a deberta-v3-small NLI cross-encoder checks whether model claims are entailed by the ground truth context; (5) Cost — tiktoken counts tokens and applies per-model pricing tables.',
      },
      {
        title: 'RAGAS Evaluation',
        text: 'The RAGAS library evaluates the full RAG quadrant: faithfulness (do claims follow from context?), answer relevancy, context precision, and context recall. These scores complement the NLI hallucination check with a semantically richer signal.',
      },
      {
        title: 'Reporters & Dashboard',
        text: 'Results are output as a Rich-formatted terminal table, a self-contained HTML report with Plotly visualizations, and a JSON export for programmatic use. A Streamlit dashboard enables multi-run comparison with KPI cards, latency bars, accuracy/hallucination/cost charts, a RAGAS radar plot, and CSV export.',
      },
    ],
    results: [
      'llama-3.3-70b achieves P50 latency of 1,956ms and TTFT of 245ms — 16× faster TTFT than llama-3.1-8b',
      'llama-3.1-8b delivers comparable semantic similarity (0.852 vs 0.880) at 10× lower cost per query',
      '0% hallucination rate on the AI/ML Q&A benchmark for both Groq models via NLI cross-encoder',
      '95 automated tests across metrics, runners, and reporters ensure evaluation reproducibility',
      'Docker + HuggingFace Spaces deployment allows the dashboard to run anywhere without local setup',
    ],
    highlights: [
      'Async parallel evaluation across 6 models from 3 providers simultaneously',
      'NLI cross-encoder (deberta-v3-small) for hallucination detection',
      'RAGAS suite: faithfulness, relevancy, context precision & recall',
      'Self-contained HTML reports with Plotly + Streamlit multi-run dashboard',
      'BaseRunner interface makes new LLM providers a one-file addition',
      '95 tests with pytest for reproducible, CI-ready benchmarking',
    ],
    techStack: [
      { label: 'Evaluation', items: ['RAGAS', 'sentence-transformers', 'deberta-v3-small'] },
      { label: 'LLM Clients', items: ['OpenAI SDK', 'Anthropic SDK', 'Groq SDK'] },
      { label: 'Infrastructure', items: ['asyncio', 'Pydantic v2', 'tiktoken'] },
      { label: 'Reporting', items: ['Streamlit', 'Plotly', 'Rich', 'Docker'] },
    ],
  },
  {
    id: 3,
    slug: 'documind',
    title: 'DocuMind',
    tagline: 'Multi-agent research that reads your documents and writes cited reports — in seconds.',
    description: 'Enterprise-grade multi-agent RAG research platform on AWS. LangGraph orchestrates a 4-agent CrewAI pipeline (Researcher → Analyst → Writer → Critic) that produces fully cited reports using hybrid pgvector + BM25 retrieval with CrossEncoder reranking. Deployed on EC2 behind CloudFront with RDS PostgreSQL, Step Functions, Bedrock Claude Haiku, and Claude Desktop MCP integration.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/DocuMind',
    demo: 'https://d2ivfev3xe6utf.cloudfront.net',
    category: 'ai',
    categoryLabel: 'AI / LLM',
    catIcon: 'fas fa-brain',
    metric: '15ms RAG · 400ms Ingest',
    tags: ['Multi-Agent', 'RAG', 'LangGraph', 'AWS Bedrock'],
    background:
      "Enterprise knowledge is trapped in PDFs, internal wikis, and siloed documentation systems. When engineers need answers, they spend hours manually searching across sources — and still miss crucial context. DocuMind replaces that with an enterprise-grade multi-agent research platform deployed on AWS that synthesizes across custom knowledge bases and produces structured, cited reports. The key architectural decisions: hybrid retrieval combining pgvector dense search with BM25 sparse matching, fused via Reciprocal Rank Fusion (RRF k=60) and reranked with a CrossEncoder — achieving higher recall and precision than either approach alone. Document ingestion runs through an asynchronous AWS Step Functions pipeline (S3 → Lambda parse via Textract → Lambda embed via Bedrock Titan Embed v2 → Lambda store into pgvector), keeping the API non-blocking even for complex multi-page PDFs.",
    workflow: [
      {
        title: 'Document Ingestion Pipeline',
        text: 'Users upload documents (PDF, DOCX) or provide URLs. An AWS Step Functions 3-stage pipeline handles ingestion asynchronously: Lambda parses content (pymupdf for PDFs, Amazon Textract for complex docs), Lambda embeds chunks using Bedrock Titan Embed v2 (1024-dim vectors), and Lambda stores into RDS pgvector with SHA-256 idempotent deduplication — typical ingest is 400–800ms.',
      },
      {
        title: 'Hybrid RAG Retrieval',
        text: 'On each query, pgvector retrieves semantically similar chunks via dense embedding search while BM25 retrieves keyword-matched chunks. Scores are fused using Reciprocal Rank Fusion (RRF k=60), then a CrossEncoder (ms-marco-MiniLM-L-6-v2) reranks the top candidates — ~15ms p50 retrieval latency.',
      },
      {
        title: '4-Agent Research Pipeline',
        text: 'LangGraph routes the query through a typed state machine of four CrewAI agents powered by Bedrock Claude Haiku: Researcher (gathers and synthesizes context from retrieved chunks), Analyst (identifies gaps and validates claims), Writer (drafts the structured report), and Critic (challenges accuracy). The critic→revise loop runs up to 2 iterations before finalizing.',
      },
      {
        title: 'Citation-Grounded Output',
        text: 'Every claim in the final report is traced back to a source chunk with page-level provenance. The Critic agent catches hallucinations before reaching the user. A human-in-the-loop approval mechanism allows engineer review before the report is delivered.',
      },
      {
        title: 'AWS Infrastructure & MCP Integration',
        text: '3-tier deployment: CloudFront CDN → EC2 t3.micro (FastAPI + Streamlit + nginx) → RDS PostgreSQL 15 with pgvector. Supporting services: S3 (document storage), SQS ingestion queue with DLQ, DynamoDB (job tracking), Lambda, Step Functions, CloudWatch. Claude Desktop MCP integration exposes DocuMind as a callable tool in extended AI conversations.',
      },
    ],
    results: [
      'PDF ingestion: ~176ms for 15-page papers; full pipeline 400–800ms; 3.5s for complex arxiv PDFs',
      'RAG retrieval at ~15ms p50 — pgvector dense + BM25 sparse fused via RRF with CrossEncoder reranking',
      'Hybrid retrieval achieves higher recall than dense-only or sparse-only approaches on internal benchmarks',
      'RAGAS evaluation integrated — faithfulness, answer relevancy, context precision & recall (target ≥0.60)',
      'Claude Desktop MCP integration enables DocuMind as a reusable research tool in AI workflows',
    ],
    highlights: [
      'Hybrid RAG: pgvector dense + BM25 sparse → Reciprocal Rank Fusion → CrossEncoder reranking',
      'LangGraph state machine with 4-agent CrewAI crew: Researcher → Analyst → Writer → Critic',
      'AWS Step Functions ingestion: S3 → Textract → Bedrock Titan Embed v2 → pgvector',
      'Amazon Bedrock: Claude Haiku for agents + Titan Embed v2 (1024-dim) for embeddings',
      'CloudFront → EC2 → RDS PostgreSQL 15 with pgvector — full AWS 3-tier deployment',
      'Claude Desktop MCP tool integration + RAGAS evaluation pipeline',
    ],
    techStack: [
      { label: 'Agent Framework', items: ['LangGraph', 'CrewAI', 'LiteLLM'] },
      { label: 'Retrieval', items: ['pgvector', 'BM25', 'RRF Fusion', 'CrossEncoder'] },
      { label: 'AWS', items: ['Bedrock', 'Step Functions', 'Lambda', 'RDS', 'S3', 'CloudFront'] },
      { label: 'Interface', items: ['Streamlit', 'FastAPI', 'MCP SDK'] },
    ],
  },
  {
    id: 4,
    slug: 'project-aegis',
    title: 'Project Aegis',
    tagline: 'A self-healing data pipeline that detects drift and repairs itself — before your models silently fail.',
    description: 'Self-healing data quality system that automatically detects and repairs data drift using Evidently AI and DuckDB streaming. Scales from cloud (200MB) to local (100GB+) with a hybrid architecture and Streamlit dashboard.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/project-aegis',
    category: 'ml',
    categoryLabel: 'ML / MLOps',
    catIcon: 'fas fa-chart-line',
    metric: '<60s Detection',
    tags: ['DuckDB', 'Evidently AI', 'Polars', 'Streamlit'],
    background:
      "Data drift is silent and deadly. Production ML models degrade gradually as input distributions shift — often with no visible errors until model accuracy has already collapsed. Most solutions detect drift after the fact; Aegis is designed to detect and repair drift automatically, keeping data pipelines healthy before downstream models are affected. The hybrid architecture (DuckDB for streaming analytics + Polars for batch processing) enables the system to scale from small cloud deployments to large on-premise datasets without architectural changes.",
    workflow: [
      {
        title: 'Continuous Data Ingestion',
        text: 'Data streams into the pipeline in real-time or in micro-batches. DuckDB\'s columnar streaming engine handles ingestion with sub-second latency at scale.',
      },
      {
        title: 'Statistical Drift Detection',
        text: 'Evidently AI monitors feature distributions against reference baselines using PSI, KS test, and Jensen-Shannon divergence. Alerts are generated when drift exceeds configurable thresholds.',
      },
      {
        title: 'Automated Repair Triggers',
        text: 'When drift is detected, Aegis triggers automated repair actions: outlier capping, imputation, distribution normalization, or flagging for human review depending on severity.',
      },
      {
        title: 'Polars Batch Processing',
        text: 'Polars handles the high-throughput batch transformations needed for large-scale repair operations — significantly faster than Pandas for 100GB+ datasets.',
      },
      {
        title: 'Streamlit Dashboard',
        text: 'A real-time Streamlit dashboard visualizes drift metrics, repair actions taken, and pipeline health over time — giving data engineers full observability.',
      },
    ],
    results: [
      'Scales seamlessly from 200MB cloud to 100GB+ local datasets without code changes',
      'Mean time to drift detection reduced to under 60 seconds with DuckDB streaming',
      'Automated repair recovers ~85% of common drift patterns without human intervention',
      'Streamlit dashboard provides full pipeline observability with sub-10s refresh',
    ],
    highlights: [
      'DuckDB columnar streaming for sub-second ingestion analytics',
      'Evidently AI statistical drift detection (PSI, KS, Jensen-Shannon)',
      'Polars for high-throughput batch repair operations',
      'Hybrid cloud/local architecture with no code changes required',
      'Real-time Streamlit observability dashboard',
    ],
    techStack: [
      { label: 'Analytics', items: ['DuckDB', 'Polars'] },
      { label: 'Drift Detection', items: ['Evidently AI', 'Statistical Tests'] },
      { label: 'Interface', items: ['Streamlit'] },
      { label: 'Language', items: ['Python'] },
    ],
  },
  {
    id: 5,
    slug: 'chain-of-thought-faithfulness',
    title: 'Chain-of-Thought Faithfulness',
    tagline: 'Does your LLM\'s reasoning actually drive its answers? The data says: probably not.',
    description: 'Research into whether LLM chain-of-thought reasoning actually influences predictions using Negative Preference Optimization. Found fine-tuning on high-quality CoT reduces faithfulness by 56–75% — a data curation problem, not training.',
    language: 'Jupyter Notebook',
    langIcon: 'fas fa-book-open',
    github: 'https://github.com/madhavanbalaji02/Chain-of-Thought-Faithfulness',
    category: 'ai',
    categoryLabel: 'AI / LLM',
    catIcon: 'fas fa-brain',
    metric: '↓56–75% Faithful',
    tags: ['LLMs', 'NPO', 'NLP', 'Research'],
    background:
      "Chain-of-thought (CoT) prompting produces reasoning traces that look coherent — but are they causally connected to the model's final answer? Or are they post-hoc rationalizations of a decision made elsewhere in the model? This distinction matters enormously for AI safety and interpretability. If CoT is just a narrative layer, then 'reasoning-based' safety interventions are built on sand. This project investigates CoT faithfulness using causal intervention: does perturbing the reasoning trace change the model's output? And critically: does fine-tuning on high-quality CoT help or hurt?",
    workflow: [
      {
        title: 'Faithfulness Measurement',
        text: 'Faithfulness is operationalized as the causal impact of the reasoning trace on the final prediction. Traces are perturbed and the change in output is measured.',
      },
      {
        title: 'Negative Preference Optimization (NPO)',
        text: 'NPO fine-tunes the model to prefer outputs where the CoT and the answer are causally linked, penalizing disconnected reasoning.',
      },
      {
        title: 'Fine-tuning Experiments',
        text: 'Models were fine-tuned on curated high-quality CoT datasets and evaluated for faithfulness — isolating whether data quality or training objective is the bottleneck.',
      },
      {
        title: 'Causal Analysis',
        text: 'Systematic causal intervention on CoT content reveals the degree to which the model\'s prediction is determined by the reasoning vs. the question alone.',
      },
    ],
    results: [
      'Fine-tuning on high-quality CoT reduces faithfulness by 56–75% — counterintuitive but robust finding',
      'The root cause is data curation, not the training objective — models learn to produce impressive reasoning without using it',
      'NPO partially recovers faithfulness but is insufficient alone',
      'Findings suggest CoT-based safety interventions need structural changes, not just better data',
    ],
    highlights: [
      'Causal intervention methodology for measuring CoT faithfulness',
      'Negative Preference Optimization (NPO) implementation',
      'Counterintuitive finding: better CoT data → less faithful reasoning',
      'NLP evaluation metrics for reasoning trace quality',
    ],
    techStack: [
      { label: 'Training', items: ['HuggingFace', 'NPO', 'Fine-tuning'] },
      { label: 'Evaluation', items: ['NLP Metrics', 'Causal Analysis'] },
      { label: 'Stack', items: ['Python', 'Jupyter', 'PyTorch'] },
    ],
  },
  {
    id: 6,
    slug: 'vectorgaze',
    title: 'VectorGaze',
    tagline: 'Natural language safety queries on live video — zero training data required.',
    description: 'Edge AI system detecting workplace safety violations from video using natural language queries — no training data required. Combines CLIP zero-shot embeddings, Moondream2 reasoning, and LanceDB vector search on Apple Silicon.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/VectorGaze',
    category: 'cv',
    categoryLabel: 'Computer Vision',
    catIcon: 'fas fa-eye',
    metric: 'Zero-Shot (no labels)',
    tags: ['CLIP', 'Zero-Shot', 'LanceDB', 'Edge AI'],
    background:
      "Workplace safety monitoring traditionally requires expensive labeled video datasets to train a custom detector for each violation type. If a new hazard emerges (a new machine, a new PPE requirement), you're back to data collection. VectorGaze eliminates this bottleneck by using CLIP's zero-shot visual-language alignment: instead of training a detector, you describe the violation in natural language, and CLIP finds frames that semantically match. This makes the system instantly configurable for any safety scenario without a single labeled example.",
    workflow: [
      {
        title: 'Video Sampling',
        text: 'Frames are sampled from the live or recorded video stream at configurable intervals (e.g., 1 frame per second for real-time, denser for analysis).',
      },
      {
        title: 'CLIP Visual Embedding',
        text: 'Each frame is encoded by CLIP\'s vision encoder into a 512-dimensional embedding that captures the visual semantics of the scene.',
      },
      {
        title: 'Query Embedding & Vector Search',
        text: 'The natural language safety query (e.g., "worker not wearing hard hat") is encoded by CLIP\'s text encoder. LanceDB performs approximate nearest-neighbor search across all frame embeddings.',
      },
      {
        title: 'Moondream2 Confirmation',
        text: 'Top candidate frames are passed to Moondream2 VLM for detailed visual reasoning, reducing false positives before alerting.',
      },
      {
        title: 'Edge Deployment',
        text: 'Entire pipeline runs on Apple Silicon (M-series) with Metal acceleration — no cloud calls, keeping footage private and latency sub-second.',
      },
    ],
    results: [
      'Zero-shot detection of arbitrary safety violations with no labeled training data',
      'LanceDB enables real-time vector search across thousands of frame embeddings',
      'Moondream2 reasoning step reduces false positive rate significantly',
      'Fully on-device on Apple Silicon — no data leaves the local network',
    ],
    highlights: [
      'Zero-shot: no training data or annotation required',
      'Natural language query interface for any violation type',
      'LanceDB for efficient real-time frame similarity search',
      'Moondream2 VLM for visual reasoning confirmation',
      'Edge deployment on Apple Silicon with Metal acceleration',
    ],
    techStack: [
      { label: 'Vision-Language', items: ['CLIP', 'Moondream2'] },
      { label: 'Vector Store', items: ['LanceDB'] },
      { label: 'Hardware', items: ['Apple Silicon', 'Metal GPU'] },
      { label: 'Language', items: ['Python', 'OpenCV'] },
    ],
  },
  {
    id: 7,
    slug: 'dentavision',
    title: 'DentaVision',
    tagline: 'A Vision Transformer that diagnoses dental conditions at 92.4% accuracy — in under a second.',
    description: 'AI diagnostic system classifying dental conditions (caries, gingivitis) at 92.4% accuracy using a pretrained Vision Transformer. FastAPI backend and React frontend deliver sub-second inference for clinical use.',
    language: 'Jupyter Notebook',
    langIcon: 'fas fa-book-open',
    github: 'https://github.com/raghuveer9303/DentaVision',
    demo: 'https://dentalvision.onrender.com/',
    category: 'cv',
    categoryLabel: 'Computer Vision',
    catIcon: 'fas fa-eye',
    metric: '92.4% Accuracy',
    tags: ['ViT', 'Medical AI', 'FastAPI', 'React'],
    background:
      "Dental diagnostics are subjective, expensive, and inaccessible in underserved regions. A dentist's assessment of caries or gingivitis from an intraoral photo varies by experience and fatigue. DentaVision applies a pretrained Vision Transformer (ViT) to standardize and accelerate dental diagnosis — providing consistent, explainable classifications from dental images with sub-second inference via a clinical-ready API. The ViT architecture was chosen over CNNs for its global attention mechanism, which better captures the distributed visual patterns of dental pathology.",
    workflow: [
      {
        title: 'Vision Transformer Classification',
        text: 'A pretrained ViT-Base/16 model is fine-tuned on a curated dental image dataset. The attention mechanism allows the model to focus on distributed caries and gingivitis indicators across the entire image.',
      },
      {
        title: 'Fine-Tuning Pipeline',
        text: 'The ViT backbone is frozen; only the classification head and final transformer blocks are fine-tuned. Data augmentation (rotation, brightness, contrast jitter) expands the training distribution.',
      },
      {
        title: 'FastAPI Inference Backend',
        text: 'A FastAPI service wraps the trained model, accepting base64-encoded images and returning classification predictions with confidence scores in JSON. Designed for clinical EMR system integration.',
      },
      {
        title: 'React Clinical Frontend',
        text: 'A React interface allows clinicians to upload dental images and receive instant diagnosis with confidence breakdown — designed for low-friction clinical workflow integration.',
      },
    ],
    results: [
      '92.4% classification accuracy on caries and gingivitis detection',
      'Sub-second inference latency suitable for real-time clinical use',
      'FastAPI backend designed for EMR/EHR system integration',
      'ViT attention maps provide interpretable visual explanations for clinicians',
    ],
    highlights: [
      'Vision Transformer (ViT) with global attention for dental pathology',
      '92.4% accuracy — competitive with trained human performance',
      'FastAPI backend ready for clinical EMR integration',
      'React frontend designed for clinical workflow',
      'Interpretable attention maps for explainability',
    ],
    techStack: [
      { label: 'Model', items: ['ViT-Base/16', 'Fine-tuning'] },
      { label: 'Backend', items: ['FastAPI', 'Python'] },
      { label: 'Frontend', items: ['React'] },
      { label: 'Training', items: ['HuggingFace', 'PyTorch'] },
    ],
  },
  {
    id: 8,
    slug: 'hybrid-anime-recommender',
    title: 'Hybrid Anime Recommender',
    tagline: 'A production recommender system with full CI/CD, containerization, and K8s orchestration.',
    description: 'Production recommender combining content-based and collaborative filtering for personalized anime suggestions. Flask API, containerized via Docker and Kubernetes, with Jenkins + ArgoCD CI/CD pipelines.',
    language: 'Jupyter Notebook',
    langIcon: 'fas fa-book-open',
    github: 'https://github.com/madhavanbalaji02/Hybrid-Anime-Recommendation-System',
    category: 'ml',
    categoryLabel: 'ML / MLOps',
    catIcon: 'fas fa-chart-line',
    metric: '<5min Deploy',
    tags: ['Recommender', 'Kubernetes', 'ArgoCD', 'MLOps'],
    background:
      "Recommender systems sit at the intersection of ML and production engineering — the model is only half the challenge. This project was built to practice the full MLOps lifecycle: developing a hybrid recommender (content-based + collaborative filtering), containerizing it, deploying it to Kubernetes, and establishing automated CI/CD pipelines. The hybrid approach was chosen because neither content-based (ignores user behavior) nor collaborative filtering alone (ignores item attributes) achieves the best recommendations — combining them captures both signal types.",
    workflow: [
      {
        title: 'Content-Based Filtering',
        text: 'Anime metadata (genres, studios, rating, synopsis) is encoded using TF-IDF and cosine similarity. Items similar to previously liked content are ranked highly.',
      },
      {
        title: 'Collaborative Filtering',
        text: 'User-item interaction matrices are decomposed using matrix factorization. Latent factors capture behavioral patterns — users who liked similar anime are grouped, and their preferences propagate.',
      },
      {
        title: 'Hybrid Score Fusion',
        text: 'Content and collaborative scores are fused with a weighted combination tuned against a held-out validation set. The weights balance exploration (content) vs personalization (collaborative).',
      },
      {
        title: 'Flask API + Containerization',
        text: 'The recommender is served via a Flask API, containerized with Docker. A multi-stage Dockerfile minimizes image size for efficient Kubernetes pod spin-up.',
      },
      {
        title: 'Jenkins + ArgoCD CI/CD',
        text: 'Jenkins runs unit tests and builds Docker images on every commit. ArgoCD watches the Helm chart repository and auto-syncs Kubernetes deployments — full GitOps.',
      },
    ],
    results: [
      'Hybrid approach outperforms either content-based or collaborative filtering alone on NDCG@10',
      'Full GitOps pipeline: code push to production deployment in under 5 minutes',
      'Kubernetes deployment with auto-scaling handles traffic spikes without manual intervention',
      'Model versioning via DVC ensures reproducible recommendation behavior',
    ],
    highlights: [
      'Hybrid recommender: content-based + collaborative filtering fusion',
      'Full MLOps pipeline: Docker → Kubernetes → GitOps via ArgoCD',
      'Jenkins CI/CD with automated test and build stages',
      'Flask API optimized for low-latency recommendation serving',
      'DVC for model versioning and experiment tracking',
    ],
    techStack: [
      { label: 'ML', items: ['Collaborative Filtering', 'TF-IDF', 'Matrix Factorization'] },
      { label: 'Serving', items: ['Flask', 'Docker', 'Kubernetes'] },
      { label: 'CI/CD', items: ['Jenkins', 'ArgoCD', 'GitOps'] },
      { label: 'Tracking', items: ['DVC', 'Python'] },
    ],
  },
  {
    id: 9,
    slug: 'multi-style-image-transfer',
    title: 'Multi-Style Image Transfer',
    tagline: 'Transforms photos into Renaissance masterpieces, Van Gogh canvases, or Impressionist works — on demand.',
    description: 'Transforms photos into art using GAN-based neural style transfer and Stable Diffusion with a custom Van Gogh LoRA adapter fine-tuned on 400 paintings. Supports Renaissance, Impressionism, and more.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/multi-style-image-transfer',
    category: 'cv',
    categoryLabel: 'Computer Vision',
    catIcon: 'fas fa-eye',
    metric: '400 Paintings',
    tags: ['GAN', 'Stable Diffusion', 'LoRA', 'CV'],
    background:
      "Neural style transfer has existed since 2015, but early GAN-based approaches struggle with identity preservation and style intensity control. This project combines two paradigms: classical GAN-based neural style transfer for precise feature-level stylization, and Stable Diffusion with a custom LoRA adapter for more fluid, diffusion-based style application. The Van Gogh LoRA was fine-tuned on 400 curated paintings from the artist's distinct periods — capturing brush stroke texture, color palette, and compositional patterns that generic artistic prompts miss.",
    workflow: [
      {
        title: 'GAN-Based Style Transfer',
        text: 'The GAN approach uses a pretrained VGG network to extract content and style features. Gram matrices capture texture statistics; gradient descent iteratively blends them in the output image.',
      },
      {
        title: 'Custom Van Gogh LoRA Training',
        text: '400 Van Gogh paintings were curated, captioned, and used to fine-tune a LoRA adapter on Stable Diffusion. The adapter captures the artist\'s specific color vocabulary and brushstroke character.',
      },
      {
        title: 'Stable Diffusion Pipeline',
        text: 'With the Van Gogh LoRA loaded, img2img diffusion transforms input photos with a configurable strength parameter controlling how much of the original content is preserved.',
      },
      {
        title: 'Style Selection Interface',
        text: 'Users choose between GAN (precise, feature-level) or Diffusion (fluid, impression-level) pipelines, and select from Renaissance, Impressionism, Expressionism, or custom styles.',
      },
    ],
    results: [
      'Custom Van Gogh LoRA produces significantly more authentic stylization than generic "Van Gogh style" prompts',
      'GAN pipeline preserves structural content better for portrait and architectural subjects',
      'Diffusion pipeline produces more creative, atmospheric results for landscape subjects',
      'Two-pipeline architecture gives users meaningful stylistic control',
    ],
    highlights: [
      'Van Gogh LoRA fine-tuned on 400 curated paintings',
      'Dual pipeline: GAN (precise) + Stable Diffusion (fluid)',
      'Gram matrix-based content/style separation in GAN path',
      'Configurable style strength and content preservation',
    ],
    techStack: [
      { label: 'Generative AI', items: ['Stable Diffusion', 'LoRA', 'GAN'] },
      { label: 'Vision', items: ['VGG Features', 'Gram Matrix', 'PyTorch'] },
      { label: 'Training', items: ['HuggingFace', 'PEFT', 'Python'] },
    ],
  },
  {
    id: 10,
    slug: 'omnibridge',
    title: 'OmniBridge',
    tagline: 'Image captions that actually read the text in the image — not just describe the scene.',
    description: 'Vision-language captioning system built on BLIP-2, fine-tuned with LoRA on TextCaps. Generates accurate captions that incorporate visible text within images for significantly enhanced quality on text-heavy content.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/OmniBridge',
    category: 'cv',
    categoryLabel: 'Computer Vision',
    catIcon: 'fas fa-eye',
    metric: '0.1% Params vs full FT',
    tags: ['BLIP-2', 'LoRA', 'Fine-tuning', 'Vision-Language'],
    background:
      "Standard image captioning systems describe the visual scene but ignore text visible within the image — charts, signs, slides, product labels. This creates a major gap for real-world applications: a model that describes 'a whiteboard' instead of reading the equations on it, or 'a sign' instead of reading what it says. OmniBridge bridges this gap by fine-tuning BLIP-2 on the TextCaps dataset using LoRA — a parameter-efficient technique that adapts a large pretrained model without retraining all parameters.",
    workflow: [
      {
        title: 'Pretrained BLIP-2 Backbone',
        text: 'BLIP-2 (Bootstrapping Language-Image Pretraining) combines a frozen vision encoder, a learned Q-Former bridge, and a frozen language model to generate captions from images.',
      },
      {
        title: 'LoRA Fine-Tuning',
        text: 'Low-Rank Adaptation (LoRA) inserts small trainable matrices into BLIP-2\'s attention layers. This allows domain adaptation on TextCaps with minimal compute — only 0.1% of parameters are trained.',
      },
      {
        title: 'TextCaps Dataset Training',
        text: 'TextCaps provides image-caption pairs where captions specifically incorporate OCR text visible in the image. The model learns to ground language in both visual content and readable text.',
      },
      {
        title: 'Inference Pipeline',
        text: 'At inference, OmniBridge produces captions that seamlessly integrate scene description with in-image text — far more useful for accessibility, document indexing, and multimodal search.',
      },
    ],
    results: [
      'Significantly improved caption quality on text-heavy images vs base BLIP-2',
      'LoRA fine-tuning achieved results with a fraction of the compute of full fine-tuning',
      'Model correctly reads and incorporates visible text (signs, labels, slides) into generated captions',
      'TextCaps CIDEr score improved substantially over the base BLIP-2 baseline',
    ],
    highlights: [
      'BLIP-2 vision-language architecture with Q-Former bridge',
      'LoRA: only 0.1% of parameters fine-tuned, full-model quality gains',
      'TextCaps dataset — captions grounded in in-image OCR text',
      'Multimodal grounding: visual scene + readable text combined',
    ],
    techStack: [
      { label: 'Model', items: ['BLIP-2', 'LoRA', 'Q-Former'] },
      { label: 'Dataset', items: ['TextCaps', 'OCR-grounded captions'] },
      { label: 'Training', items: ['HuggingFace', 'PyTorch', 'PEFT'] },
    ],
  },
  {
    id: 11,
    slug: 'llm-inference-playground',
    title: 'LLM Inference Playground',
    tagline: 'A hands-on system that exposes what most LLM APIs deliberately hide.',
    description: 'Educational system exposing explicit control over transformer logit space — manual temperature scaling, top-K, and nucleus sampling without HuggingFace defaults. Tracks TTFT and throughput with a FastAPI + React interface.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/LLM-Inference-Education-Playground-',
    category: 'ai',
    categoryLabel: 'AI / LLM',
    catIcon: 'fas fa-brain',
    metric: '↓TTFT Tracked',
    tags: ['PyTorch', 'FastAPI', 'Transformers', 'React'],
    background:
      "Most LLM APIs hide the mechanics: you set a temperature slider and get text back. But understanding what's happening in the logit space — how temperature reshapes the probability distribution, why top-K and nucleus sampling behave differently in edge cases — is essential for anyone building serious LLM applications. This playground was built as an educational tool to expose these mechanics explicitly: no HuggingFace generate() defaults, manual implementations of each sampling strategy, and live tracking of time-to-first-token (TTFT) and throughput.",
    workflow: [
      {
        title: 'Manual Logit Processing',
        text: 'After the forward pass, raw logits are processed manually: temperature scaling, top-K filtering, and nucleus (top-p) sampling are implemented from scratch — not using library defaults.',
      },
      {
        title: 'Token Generation Loop',
        text: 'The autoregressive generation loop tracks TTFT (latency to first token) and throughput (tokens per second) at each step, surfacing where bottlenecks occur.',
      },
      {
        title: 'FastAPI Backend',
        text: 'A FastAPI server exposes endpoints for model loading, parameter configuration, and generation — allowing the React frontend to issue real-time inference requests.',
      },
      {
        title: 'React Interface',
        text: 'The React frontend provides interactive sliders for temperature, top-K, and top-p parameters. Generated text and performance metrics update in real time, enabling side-by-side comparison of sampling strategies.',
      },
    ],
    results: [
      'Educational tool used to demonstrate LLM decoding mechanics in classroom settings',
      'Manual sampling implementations reveal subtle behavioral differences vs library defaults',
      'TTFT tracking enables fine-grained latency analysis across model sizes',
      'React UI makes sampling strategies intuitively comparable through live parameter tuning',
    ],
    highlights: [
      'Manual temperature / top-K / nucleus sampling — no library defaults',
      'TTFT and throughput tracking at each generation step',
      'FastAPI backend with real-time inference endpoints',
      'React frontend with live parameter sliders and comparison',
    ],
    techStack: [
      { label: 'ML', items: ['PyTorch', 'HuggingFace Transformers'] },
      { label: 'Backend', items: ['FastAPI', 'Python'] },
      { label: 'Frontend', items: ['React', 'Tailwind CSS'] },
    ],
  },
  {
    id: 12,
    slug: 'daily-tech-intel',
    title: 'Daily Tech Intel',
    tagline: '3-tier semantic pipeline that scrapes, translates, and summarizes 100+ global tech sources daily.',
    description: 'End-to-end LLM application: a Cloudflare Worker fetches 10 RSS feeds (including Japanese and German sources), passes 100+ articles through Claude for semantic curation into 3 personalized sections, and caches results in Cloudflare KV. On-demand deep analysis with 7-day per-article caching. Built into this portfolio.',
    language: 'JavaScript',
    langIcon: 'fab fa-js',
    demo: '/#/tech-news',
    category: 'ai',
    categoryLabel: 'AI / LLM',
    catIcon: 'fas fa-newspaper',
    metric: '100+ Sources Daily',
    tags: ['Claude API', 'Cloudflare Workers', 'RAG', 'RSS'],
    background:
      "Keeping up with AI/ML research across English, Japanese, and German sources is a full-time job. Daily Tech Intel automates this: a Cloudflare Worker runs a 3-tier semantic pipeline — ingesting RSS feeds from 10 sources, passing 100+ raw articles to Claude for semantic filtering and summarization into 3 personalized sections (For You, My Stack, Around the World), and persisting results in Cloudflare KV with a 24-hour TTL. Non-English articles are translated to English in the same Claude pass. On-demand article analysis triggers a second Claude call for a 5–7 sentence deep-dive with key takeaways, cached per-article for 7 days. Prompt caching cuts input token costs ~90% on repeated section refreshes.",
    workflow: [
      {
        title: 'RSS Ingestion Layer',
        text: 'A Cloudflare Worker fetches 10 RSS feeds in parallel via Promise.allSettled — TechCrunch, The Verge, Hacker News, Ars Technica, HuggingFace Blog, ArXiv CS.AI/LG/CV, Gigazine (🇯🇵), and Golem.de (🇩🇪). Custom XML parser handles both RSS 2.0 and Atom formats with CDATA stripping.',
      },
      {
        title: 'Semantic Curation via Claude',
        text: 'All 100+ articles are batched into a single Claude claude-sonnet-4-6 call with a prompt-cached system block. Claude selects 12 articles per section — For You (broad AI/ML), My Stack (MLOps, alignment, vision, recsys), Around the World (global/translated) — and writes a 2-sentence summary per article.',
      },
      {
        title: 'Translation Pipeline',
        text: 'Japanese and German articles are translated to English inline during the curation pass — no separate translation call. Claude sets wasTranslated: true and countryFlag on each non-English article so the UI can surface the origin.',
      },
      {
        title: 'KV Caching & Delivery',
        text: 'Curated results are stored in Cloudflare KV with a 24-hour TTL. A daily Cron Trigger at 06:00 UTC pre-populates the cache so HTTP requests always read from KV instantly. A background refresh (ctx.waitUntil) handles cache misses without blocking the response.',
      },
      {
        title: 'On-Demand Deep Analysis',
        text: 'Clicking any article card triggers a second Claude call for a 5–7 sentence deep-dive and 4 key takeaways, targeted at ML practitioners. Results are cached per article URL for 7 days in KV — repeated clicks are instant.',
      },
    ],
    results: [
      '36 curated articles daily across 3 personalized sections from 100+ raw RSS entries',
      'International sources (Japanese, German) translated to English in a single Claude pass',
      'Prompt caching reduces input token cost ~90% on same-day cache refreshes',
      'Per-article deep analysis cached 7 days — second click always instant',
      'Zero cold-start: Cloudflare Cron Trigger pre-populates KV at 06:00 UTC daily',
    ],
    highlights: [
      '10 RSS feeds: TechCrunch, The Verge, HN, Ars Technica, HuggingFace, ArXiv CS.AI/LG/CV, Gigazine 🇯🇵, Golem.de 🇩🇪',
      'Single-pass semantic curation + translation via Claude claude-sonnet-4-6 with ephemeral prompt caching',
      'Cloudflare Workers + KV: globally distributed, zero cold-start, free tier',
      'Cron Trigger for daily pre-population; ctx.waitUntil for background cache-miss refresh',
      '3-section personalization: For You / My Stack / Around the World',
      'On-demand article deep-dive: 5–7 sentence analysis + 4 key takeaways, 7-day per-article cache',
    ],
    techStack: [
      { label: 'AI', items: ['Claude claude-sonnet-4-6', 'Prompt Caching', 'On-demand Analysis'] },
      { label: 'Infrastructure', items: ['Cloudflare Workers', 'Cloudflare KV', 'Cron Triggers'] },
      { label: 'Data', items: ['RSS 2.0', 'Atom Feeds', 'Custom XML Parser', 'Multi-language Translation'] },
      { label: 'Frontend', items: ['React 18', 'HashRouter', 'CSS Custom Properties'] },
    ],
  },
];
