export const projectsData = [
  {
    id: 1,
    slug: 'sovereign-sre',
    title: 'Sovereign SRE',
    tagline: 'Autonomous infrastructure that detects, diagnoses, and fixes production issues — without paging anyone.',
    description: 'Autonomous infrastructure system that detects, diagnoses, and fixes production issues using AI agents with codebase awareness — eliminating manual SRE intervention. Multi-agent AI with human approval gates deploys fixes safely.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/Sovereign-SRE',
    category: 'ai',
    categoryLabel: 'AI / LLM',
    catIcon: 'fas fa-brain',
    tags: ['LangGraph', 'CrewAI', 'Ollama', 'ChromaDB'],
    background:
      "Production systems fail in unpredictable ways. Traditional SRE relies on human engineers on-call, following runbooks, and debugging under extreme pressure — an expensive, error-prone process at scale. Sovereign SRE explores whether multi-agent AI can autonomously handle this loop: detect → diagnose → fix → verify, with a human-in-the-loop approval gate that prevents unsafe automated deployments. The core insight is that most production incidents are variations of known failure patterns — and if you can embed codebase awareness into the agent's reasoning, you can generate context-appropriate fixes rather than generic remediation steps.",
    workflow: [
      {
        title: 'Anomaly Detection',
        text: 'Prometheus integration continuously monitors production metrics. Threshold breaches or anomalous patterns trigger the agent pipeline.',
      },
      {
        title: 'Multi-Agent Orchestration',
        text: 'LangGraph orchestrates three specialized agents: Monitor Agent (classifies the incident), Diagnosis Agent (traces root cause using codebase embeddings), and Fix Agent (proposes a remediation plan).',
      },
      {
        title: 'Codebase-Aware Diagnosis',
        text: 'ChromaDB stores vector embeddings of the entire codebase. The Diagnosis Agent retrieves semantically relevant code context to understand why an error is occurring — not just where.',
      },
      {
        title: 'Local LLM Reasoning',
        text: 'Ollama provides local inference (no cloud API dependency), keeping sensitive codebase data on-premise. CrewAI manages agent role delegation and communication.',
      },
      {
        title: 'Human Approval Gate',
        text: 'Before any fix is deployed, a human operator reviews the proposed remediation. This prevents autonomous loops from cascading incorrectly.',
      },
    ],
    results: [
      'Reduced mean time to diagnosis (MTTD) for common failure patterns by ~70% vs manual runbook approach',
      'Context-aware fixes generated using codebase embeddings outperform generic remediation templates',
      'Full local inference via Ollama ensures no sensitive code leaves the environment',
      'Human approval gate eliminates the risk of runaway autonomous remediation',
    ],
    highlights: [
      'Codebase-aware diagnosis via ChromaDB vector embeddings',
      'LangGraph multi-agent graph with typed state',
      'Fully local inference — no external API calls',
      'Human-in-the-loop safety gate before any deployment',
      'CrewAI for structured agent role management',
    ],
    techStack: [
      { label: 'Orchestration', items: ['LangGraph', 'CrewAI'] },
      { label: 'Inference', items: ['Ollama', 'Local LLM'] },
      { label: 'Vector Store', items: ['ChromaDB'] },
      { label: 'Monitoring', items: ['Prometheus', 'Python'] },
    ],
  },
  {
    id: 2,
    slug: 'documind',
    title: 'DocuMind',
    tagline: 'Multi-agent research that reads your documents and writes cited reports — in seconds.',
    description: 'Multi-agent research platform using LangGraph and CrewAI to produce cited reports from custom knowledge bases. Combines hybrid RAG (dense + sparse) with REST APIs, Streamlit, and Claude Desktop MCP integration.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/DocuMind',
    category: 'ai',
    categoryLabel: 'AI / LLM',
    catIcon: 'fas fa-brain',
    tags: ['Multi-Agent', 'RAG', 'LangGraph', 'CrewAI'],
    background:
      "Enterprise knowledge is trapped in PDFs, internal wikis, and siloed documentation systems. When engineers need answers, they spend hours manually searching across sources — and still miss crucial context. DocuMind replaces that with a multi-agent research platform that synthesizes across custom knowledge bases and produces structured, cited reports. The key architectural decision was hybrid retrieval: combining dense semantic search (FAISS) with sparse keyword matching (BM25) captures both conceptual relevance and precise terminology — something neither approach achieves alone.",
    workflow: [
      {
        title: 'Document Ingestion',
        text: 'Users upload documents (PDF, DOCX, text). They are chunked using semantic boundaries and embedded with both dense (vector) and sparse (BM25) representations.',
      },
      {
        title: 'Hybrid RAG Retrieval',
        text: 'On each query, FAISS retrieves semantically similar chunks while BM25 retrieves exact-match relevant chunks. Scores are fused for final ranking — maximizing recall.',
      },
      {
        title: 'Multi-Agent Research Pipeline',
        text: 'LangGraph routes the query through three agent roles via CrewAI: Researcher (gathers context), Critic (challenges accuracy), Editor (synthesizes final report).',
      },
      {
        title: 'Citation-Grounded Output',
        text: 'Every claim in the report is traced back to a source chunk. Hallucinations are caught by the Critic agent before reaching the user.',
      },
      {
        title: 'MCP Integration',
        text: 'Claude Desktop MCP integration allows deep research sessions where Claude can call the DocuMind API as a tool during extended conversations.',
      },
    ],
    results: [
      'Research reports with full citations generated in under 30 seconds',
      'Hybrid RAG improves recall by ~30% over dense-only retrieval on internal benchmarks',
      'Multi-agent critic loop reduces hallucination rate significantly vs single-pass LLM output',
      'Claude Desktop MCP integration enables DocuMind as a reusable tool in AI workflows',
    ],
    highlights: [
      'Hybrid RAG: FAISS dense + BM25 sparse retrieval fusion',
      'LangGraph agent graph with typed state transitions',
      'Researcher / Critic / Editor agent roles via CrewAI',
      'Claude Desktop MCP tool integration',
      'Streamlit frontend + REST API backend',
    ],
    techStack: [
      { label: 'Agent Framework', items: ['LangGraph', 'CrewAI'] },
      { label: 'Retrieval', items: ['FAISS', 'BM25', 'Hybrid RAG'] },
      { label: 'Interface', items: ['Streamlit', 'FastAPI', 'REST API'] },
      { label: 'AI', items: ['Claude (MCP)', 'Embeddings'] },
    ],
  },
  {
    id: 3,
    slug: 'vectorgaze',
    title: 'VectorGaze',
    tagline: 'Natural language safety queries on live video — zero training data required.',
    description: 'Edge AI system detecting workplace safety violations from video using natural language queries — no training data required. Combines CLIP zero-shot embeddings, Moondream2 reasoning, and LanceDB vector search on Apple Silicon.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/VectorGaze',
    category: 'cv',
    categoryLabel: 'Computer Vision',
    catIcon: 'fas fa-eye',
    tags: ['CLIP', 'Zero-Shot', 'LanceDB', 'Edge AI'],
    background:
      "Workplace safety monitoring traditionally requires expensive labeled video datasets to train a custom detector for each violation type. If a new hazard emerges (a new machine, a new PPE requirement), you're back to data collection. VectorGaze eliminates this bottleneck by using CLIP's zero-shot visual-language alignment: instead of training a detector, you describe the violation in natural language, and CLIP finds frames that semantically match. This makes the system instantly configurable for any safety scenario without a single labeled example.",
    workflow: [
      {
        title: 'Video Sampling',
        text: 'Frames are sampled from the live or recorded video stream at configurable intervals (e.g., 1 frame per second for real-time, denser for analysis).',
      },
      {
        title: 'CLIP Visual Embedding',
        text: 'Each frame is encoded by CLIP\'s vision encoder into a 512-dimensional embedding that captures the visual semantics of the scene.',
      },
      {
        title: 'Query Embedding & Vector Search',
        text: 'The natural language safety query (e.g., "worker not wearing hard hat") is encoded by CLIP\'s text encoder. LanceDB performs approximate nearest-neighbor search across all frame embeddings.',
      },
      {
        title: 'Moondream2 Confirmation',
        text: 'Top candidate frames are passed to Moondream2 VLM for detailed visual reasoning, reducing false positives before alerting.',
      },
      {
        title: 'Edge Deployment',
        text: 'Entire pipeline runs on Apple Silicon (M-series) with Metal acceleration — no cloud calls, keeping footage private and latency sub-second.',
      },
    ],
    results: [
      'Zero-shot detection of arbitrary safety violations with no labeled training data',
      'LanceDB enables real-time vector search across thousands of frame embeddings',
      'Moondream2 reasoning step reduces false positive rate significantly',
      'Fully on-device on Apple Silicon — no data leaves the local network',
    ],
    highlights: [
      'Zero-shot: no training data or annotation required',
      'Natural language query interface for any violation type',
      'LanceDB for efficient real-time frame similarity search',
      'Moondream2 VLM for visual reasoning confirmation',
      'Edge deployment on Apple Silicon with Metal acceleration',
    ],
    techStack: [
      { label: 'Vision-Language', items: ['CLIP', 'Moondream2'] },
      { label: 'Vector Store', items: ['LanceDB'] },
      { label: 'Hardware', items: ['Apple Silicon', 'Metal GPU'] },
      { label: 'Language', items: ['Python', 'OpenCV'] },
    ],
  },
  {
    id: 4,
    slug: 'chain-of-thought-faithfulness',
    title: 'Chain-of-Thought Faithfulness',
    tagline: 'Does your LLM\'s reasoning actually drive its answers? The data says: probably not.',
    description: 'Research into whether LLM chain-of-thought reasoning actually influences predictions using Negative Preference Optimization. Found fine-tuning on high-quality CoT reduces faithfulness by 56–75% — a data curation problem, not training.',
    language: 'Jupyter Notebook',
    langIcon: 'fas fa-book-open',
    github: 'https://github.com/madhavanbalaji02/Chain-of-Thought-Faithfulness',
    category: 'ai',
    categoryLabel: 'AI / LLM',
    catIcon: 'fas fa-brain',
    tags: ['LLMs', 'NPO', 'NLP', 'Research'],
    background:
      "Chain-of-thought (CoT) prompting produces reasoning traces that look coherent — but are they causally connected to the model's final answer? Or are they post-hoc rationalizations of a decision made elsewhere in the model? This distinction matters enormously for AI safety and interpretability. If CoT is just a narrative layer, then 'reasoning-based' safety interventions are built on sand. This project investigates CoT faithfulness using causal intervention: does perturbing the reasoning trace change the model's output? And critically: does fine-tuning on high-quality CoT help or hurt?",
    workflow: [
      {
        title: 'Faithfulness Measurement',
        text: 'Faithfulness is operationalized as the causal impact of the reasoning trace on the final prediction. Traces are perturbed and the change in output is measured.',
      },
      {
        title: 'Negative Preference Optimization (NPO)',
        text: 'NPO fine-tunes the model to prefer outputs where the CoT and the answer are causally linked, penalizing disconnected reasoning.',
      },
      {
        title: 'Fine-tuning Experiments',
        text: 'Models were fine-tuned on curated high-quality CoT datasets and evaluated for faithfulness — isolating whether data quality or training objective is the bottleneck.',
      },
      {
        title: 'Causal Analysis',
        text: 'Systematic causal intervention on CoT content reveals the degree to which the model\'s prediction is determined by the reasoning vs. the question alone.',
      },
    ],
    results: [
      'Fine-tuning on high-quality CoT reduces faithfulness by 56–75% — counterintuitive but robust finding',
      'The root cause is data curation, not the training objective — models learn to produce impressive reasoning without using it',
      'NPO partially recovers faithfulness but is insufficient alone',
      'Findings suggest CoT-based safety interventions need structural changes, not just better data',
    ],
    highlights: [
      'Causal intervention methodology for measuring CoT faithfulness',
      'Negative Preference Optimization (NPO) implementation',
      'Counterintuitive finding: better CoT data → less faithful reasoning',
      'NLP evaluation metrics for reasoning trace quality',
    ],
    techStack: [
      { label: 'Training', items: ['HuggingFace', 'NPO', 'Fine-tuning'] },
      { label: 'Evaluation', items: ['NLP Metrics', 'Causal Analysis'] },
      { label: 'Stack', items: ['Python', 'Jupyter', 'PyTorch'] },
    ],
  },
  {
    id: 5,
    slug: 'omnibridge',
    title: 'OmniBridge',
    tagline: 'Image captions that actually read the text in the image — not just describe the scene.',
    description: 'Vision-language captioning system built on BLIP-2, fine-tuned with LoRA on TextCaps. Generates accurate captions that incorporate visible text within images for significantly enhanced quality on text-heavy content.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/OmniBridge',
    category: 'cv',
    categoryLabel: 'Computer Vision',
    catIcon: 'fas fa-eye',
    tags: ['BLIP-2', 'LoRA', 'Fine-tuning', 'Vision-Language'],
    background:
      "Standard image captioning systems describe the visual scene but ignore text visible within the image — charts, signs, slides, product labels. This creates a major gap for real-world applications: a model that describes 'a whiteboard' instead of reading the equations on it, or 'a sign' instead of reading what it says. OmniBridge bridges this gap by fine-tuning BLIP-2 on the TextCaps dataset using LoRA — a parameter-efficient technique that adapts a large pretrained model without retraining all parameters.",
    workflow: [
      {
        title: 'Pretrained BLIP-2 Backbone',
        text: 'BLIP-2 (Bootstrapping Language-Image Pretraining) combines a frozen vision encoder, a learned Q-Former bridge, and a frozen language model to generate captions from images.',
      },
      {
        title: 'LoRA Fine-Tuning',
        text: 'Low-Rank Adaptation (LoRA) inserts small trainable matrices into BLIP-2\'s attention layers. This allows domain adaptation on TextCaps with minimal compute — only 0.1% of parameters are trained.',
      },
      {
        title: 'TextCaps Dataset Training',
        text: 'TextCaps provides image-caption pairs where captions specifically incorporate OCR text visible in the image. The model learns to ground language in both visual content and readable text.',
      },
      {
        title: 'Inference Pipeline',
        text: 'At inference, OmniBridge produces captions that seamlessly integrate scene description with in-image text — far more useful for accessibility, document indexing, and multimodal search.',
      },
    ],
    results: [
      'Significantly improved caption quality on text-heavy images vs base BLIP-2',
      'LoRA fine-tuning achieved results with a fraction of the compute of full fine-tuning',
      'Model correctly reads and incorporates visible text (signs, labels, slides) into generated captions',
      'TextCaps CIDEr score improved substantially over the base BLIP-2 baseline',
    ],
    highlights: [
      'BLIP-2 vision-language architecture with Q-Former bridge',
      'LoRA: only 0.1% of parameters fine-tuned, full-model quality gains',
      'TextCaps dataset — captions grounded in in-image OCR text',
      'Multimodal grounding: visual scene + readable text combined',
    ],
    techStack: [
      { label: 'Model', items: ['BLIP-2', 'LoRA', 'Q-Former'] },
      { label: 'Dataset', items: ['TextCaps', 'OCR-grounded captions'] },
      { label: 'Training', items: ['HuggingFace', 'PyTorch', 'PEFT'] },
    ],
  },
  {
    id: 6,
    slug: 'llm-inference-playground',
    title: 'LLM Inference Playground',
    tagline: 'A hands-on system that exposes what most LLM APIs deliberately hide.',
    description: 'Educational system exposing explicit control over transformer logit space — manual temperature scaling, top-K, and nucleus sampling without HuggingFace defaults. Tracks TTFT and throughput with a FastAPI + React interface.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/LLM-Inference-Education-Playground-',
    category: 'ai',
    categoryLabel: 'AI / LLM',
    catIcon: 'fas fa-brain',
    tags: ['PyTorch', 'FastAPI', 'Transformers', 'React'],
    background:
      "Most LLM APIs hide the mechanics: you set a temperature slider and get text back. But understanding what's happening in the logit space — how temperature reshapes the probability distribution, why top-K and nucleus sampling behave differently in edge cases — is essential for anyone building serious LLM applications. This playground was built as an educational tool to expose these mechanics explicitly: no HuggingFace generate() defaults, manual implementations of each sampling strategy, and live tracking of time-to-first-token (TTFT) and throughput.",
    workflow: [
      {
        title: 'Manual Logit Processing',
        text: 'After the forward pass, raw logits are processed manually: temperature scaling, top-K filtering, and nucleus (top-p) sampling are implemented from scratch — not using library defaults.',
      },
      {
        title: 'Token Generation Loop',
        text: 'The autoregressive generation loop tracks TTFT (latency to first token) and throughput (tokens per second) at each step, surfacing where bottlenecks occur.',
      },
      {
        title: 'FastAPI Backend',
        text: 'A FastAPI server exposes endpoints for model loading, parameter configuration, and generation — allowing the React frontend to issue real-time inference requests.',
      },
      {
        title: 'React Interface',
        text: 'The React frontend provides interactive sliders for temperature, top-K, and top-p parameters. Generated text and performance metrics update in real time, enabling side-by-side comparison of sampling strategies.',
      },
    ],
    results: [
      'Educational tool used to demonstrate LLM decoding mechanics in classroom settings',
      'Manual sampling implementations reveal subtle behavioral differences vs library defaults',
      'TTFT tracking enables fine-grained latency analysis across model sizes',
      'React UI makes sampling strategies intuitively comparable through live parameter tuning',
    ],
    highlights: [
      'Manual temperature / top-K / nucleus sampling — no library defaults',
      'TTFT and throughput tracking at each generation step',
      'FastAPI backend with real-time inference endpoints',
      'React frontend with live parameter sliders and comparison',
    ],
    techStack: [
      { label: 'ML', items: ['PyTorch', 'HuggingFace Transformers'] },
      { label: 'Backend', items: ['FastAPI', 'Python'] },
      { label: 'Frontend', items: ['React', 'Tailwind CSS'] },
    ],
  },
  {
    id: 7,
    slug: 'multi-style-image-transfer',
    title: 'Multi-Style Image Transfer',
    tagline: 'Transforms photos into Renaissance masterpieces, Van Gogh canvases, or Impressionist works — on demand.',
    description: 'Transforms photos into art using GAN-based neural style transfer and Stable Diffusion with a custom Van Gogh LoRA adapter fine-tuned on 400 paintings. Supports Renaissance, Impressionism, and more.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/multi-style-image-transfer',
    category: 'cv',
    categoryLabel: 'Computer Vision',
    catIcon: 'fas fa-eye',
    tags: ['GAN', 'Stable Diffusion', 'LoRA', 'CV'],
    background:
      "Neural style transfer has existed since 2015, but early GAN-based approaches struggle with identity preservation and style intensity control. This project combines two paradigms: classical GAN-based neural style transfer for precise feature-level stylization, and Stable Diffusion with a custom LoRA adapter for more fluid, diffusion-based style application. The Van Gogh LoRA was fine-tuned on 400 curated paintings from the artist's distinct periods — capturing brush stroke texture, color palette, and compositional patterns that generic artistic prompts miss.",
    workflow: [
      {
        title: 'GAN-Based Style Transfer',
        text: 'The GAN approach uses a pretrained VGG network to extract content and style features. Gram matrices capture texture statistics; gradient descent iteratively blends them in the output image.',
      },
      {
        title: 'Custom Van Gogh LoRA Training',
        text: '400 Van Gogh paintings were curated, captioned, and used to fine-tune a LoRA adapter on Stable Diffusion. The adapter captures the artist\'s specific color vocabulary and brushstroke character.',
      },
      {
        title: 'Stable Diffusion Pipeline',
        text: 'With the Van Gogh LoRA loaded, img2img diffusion transforms input photos with a configurable strength parameter controlling how much of the original content is preserved.',
      },
      {
        title: 'Style Selection Interface',
        text: 'Users choose between GAN (precise, feature-level) or Diffusion (fluid, impression-level) pipelines, and select from Renaissance, Impressionism, Expressionism, or custom styles.',
      },
    ],
    results: [
      'Custom Van Gogh LoRA produces significantly more authentic stylization than generic "Van Gogh style" prompts',
      'GAN pipeline preserves structural content better for portrait and architectural subjects',
      'Diffusion pipeline produces more creative, atmospheric results for landscape subjects',
      'Two-pipeline architecture gives users meaningful stylistic control',
    ],
    highlights: [
      'Van Gogh LoRA fine-tuned on 400 curated paintings',
      'Dual pipeline: GAN (precise) + Stable Diffusion (fluid)',
      'Gram matrix-based content/style separation in GAN path',
      'Configurable style strength and content preservation',
    ],
    techStack: [
      { label: 'Generative AI', items: ['Stable Diffusion', 'LoRA', 'GAN'] },
      { label: 'Vision', items: ['VGG Features', 'Gram Matrix', 'PyTorch'] },
      { label: 'Training', items: ['HuggingFace', 'PEFT', 'Python'] },
    ],
  },
  {
    id: 8,
    slug: 'project-aegis',
    title: 'Project Aegis',
    tagline: 'A self-healing data pipeline that detects drift and repairs itself — before your models silently fail.',
    description: 'Self-healing data quality system that automatically detects and repairs data drift using Evidently AI and DuckDB streaming. Scales from cloud (200MB) to local (100GB+) with a hybrid architecture and Streamlit dashboard.',
    language: 'Python',
    langIcon: 'fab fa-python',
    github: 'https://github.com/madhavanbalaji02/project-aegis',
    category: 'ml',
    categoryLabel: 'ML / MLOps',
    catIcon: 'fas fa-chart-line',
    tags: ['DuckDB', 'Evidently AI', 'Polars', 'Streamlit'],
    background:
      "Data drift is silent and deadly. Production ML models degrade gradually as input distributions shift — often with no visible errors until model accuracy has already collapsed. Most solutions detect drift after the fact; Aegis is designed to detect and repair drift automatically, keeping data pipelines healthy before downstream models are affected. The hybrid architecture (DuckDB for streaming analytics + Polars for batch processing) enables the system to scale from small cloud deployments to large on-premise datasets without architectural changes.",
    workflow: [
      {
        title: 'Continuous Data Ingestion',
        text: 'Data streams into the pipeline in real-time or in micro-batches. DuckDB\'s columnar streaming engine handles ingestion with sub-second latency at scale.',
      },
      {
        title: 'Statistical Drift Detection',
        text: 'Evidently AI monitors feature distributions against reference baselines using PSI, KS test, and Jensen-Shannon divergence. Alerts are generated when drift exceeds configurable thresholds.',
      },
      {
        title: 'Automated Repair Triggers',
        text: 'When drift is detected, Aegis triggers automated repair actions: outlier capping, imputation, distribution normalization, or flagging for human review depending on severity.',
      },
      {
        title: 'Polars Batch Processing',
        text: 'Polars handles the high-throughput batch transformations needed for large-scale repair operations — significantly faster than Pandas for 100GB+ datasets.',
      },
      {
        title: 'Streamlit Dashboard',
        text: 'A real-time Streamlit dashboard visualizes drift metrics, repair actions taken, and pipeline health over time — giving data engineers full observability.',
      },
    ],
    results: [
      'Scales seamlessly from 200MB cloud to 100GB+ local datasets without code changes',
      'Mean time to drift detection reduced to under 60 seconds with DuckDB streaming',
      'Automated repair recovers ~85% of common drift patterns without human intervention',
      'Streamlit dashboard provides full pipeline observability with sub-10s refresh',
    ],
    highlights: [
      'DuckDB columnar streaming for sub-second ingestion analytics',
      'Evidently AI statistical drift detection (PSI, KS, Jensen-Shannon)',
      'Polars for high-throughput batch repair operations',
      'Hybrid cloud/local architecture with no code changes required',
      'Real-time Streamlit observability dashboard',
    ],
    techStack: [
      { label: 'Analytics', items: ['DuckDB', 'Polars'] },
      { label: 'Drift Detection', items: ['Evidently AI', 'Statistical Tests'] },
      { label: 'Interface', items: ['Streamlit'] },
      { label: 'Language', items: ['Python'] },
    ],
  },
  {
    id: 9,
    slug: 'dentavision',
    title: 'DentaVision',
    tagline: 'A Vision Transformer that diagnoses dental conditions at 92.4% accuracy — in under a second.',
    description: 'AI diagnostic system classifying dental conditions (caries, gingivitis) at 92.4% accuracy using a pretrained Vision Transformer. FastAPI backend and React frontend deliver sub-second inference for clinical use.',
    language: 'Jupyter Notebook',
    langIcon: 'fas fa-book-open',
    github: 'https://github.com/raghuveer9303/DentaVision',
    category: 'cv',
    categoryLabel: 'Computer Vision',
    catIcon: 'fas fa-eye',
    tags: ['ViT', 'Medical AI', 'FastAPI', 'React'],
    background:
      "Dental diagnostics are subjective, expensive, and inaccessible in underserved regions. A dentist's assessment of caries or gingivitis from an intraoral photo varies by experience and fatigue. DentaVision applies a pretrained Vision Transformer (ViT) to standardize and accelerate dental diagnosis — providing consistent, explainable classifications from dental images with sub-second inference via a clinical-ready API. The ViT architecture was chosen over CNNs for its global attention mechanism, which better captures the distributed visual patterns of dental pathology.",
    workflow: [
      {
        title: 'Vision Transformer Classification',
        text: 'A pretrained ViT-Base/16 model is fine-tuned on a curated dental image dataset. The attention mechanism allows the model to focus on distributed caries and gingivitis indicators across the entire image.',
      },
      {
        title: 'Fine-Tuning Pipeline',
        text: 'The ViT backbone is frozen; only the classification head and final transformer blocks are fine-tuned. Data augmentation (rotation, brightness, contrast jitter) expands the training distribution.',
      },
      {
        title: 'FastAPI Inference Backend',
        text: 'A FastAPI service wraps the trained model, accepting base64-encoded images and returning classification predictions with confidence scores in JSON. Designed for clinical EMR system integration.',
      },
      {
        title: 'React Clinical Frontend',
        text: 'A React interface allows clinicians to upload dental images and receive instant diagnosis with confidence breakdown — designed for low-friction clinical workflow integration.',
      },
    ],
    results: [
      '92.4% classification accuracy on caries and gingivitis detection',
      'Sub-second inference latency suitable for real-time clinical use',
      'FastAPI backend designed for EMR/EHR system integration',
      'ViT attention maps provide interpretable visual explanations for clinicians',
    ],
    highlights: [
      'Vision Transformer (ViT) with global attention for dental pathology',
      '92.4% accuracy — competitive with trained human performance',
      'FastAPI backend ready for clinical EMR integration',
      'React frontend designed for clinical workflow',
      'Interpretable attention maps for explainability',
    ],
    techStack: [
      { label: 'Model', items: ['ViT-Base/16', 'Fine-tuning'] },
      { label: 'Backend', items: ['FastAPI', 'Python'] },
      { label: 'Frontend', items: ['React'] },
      { label: 'Training', items: ['HuggingFace', 'PyTorch'] },
    ],
  },
  {
    id: 10,
    slug: 'hybrid-anime-recommender',
    title: 'Hybrid Anime Recommender',
    tagline: 'A production recommender system with full CI/CD, containerization, and K8s orchestration.',
    description: 'Production recommender combining content-based and collaborative filtering for personalized anime suggestions. Flask API, containerized via Docker and Kubernetes, with Jenkins + ArgoCD CI/CD pipelines.',
    language: 'Jupyter Notebook',
    langIcon: 'fas fa-book-open',
    github: 'https://github.com/madhavanbalaji02/Hybrid-Anime-Recommendation-System',
    category: 'ml',
    categoryLabel: 'ML / MLOps',
    catIcon: 'fas fa-chart-line',
    tags: ['Recommender', 'Kubernetes', 'ArgoCD', 'MLOps'],
    background:
      "Recommender systems sit at the intersection of ML and production engineering — the model is only half the challenge. This project was built to practice the full MLOps lifecycle: developing a hybrid recommender (content-based + collaborative filtering), containerizing it, deploying it to Kubernetes, and establishing automated CI/CD pipelines. The hybrid approach was chosen because neither content-based (ignores user behavior) nor collaborative filtering alone (ignores item attributes) achieves the best recommendations — combining them captures both signal types.",
    workflow: [
      {
        title: 'Content-Based Filtering',
        text: 'Anime metadata (genres, studios, rating, synopsis) is encoded using TF-IDF and cosine similarity. Items similar to previously liked content are ranked highly.',
      },
      {
        title: 'Collaborative Filtering',
        text: 'User-item interaction matrices are decomposed using matrix factorization. Latent factors capture behavioral patterns — users who liked similar anime are grouped, and their preferences propagate.',
      },
      {
        title: 'Hybrid Score Fusion',
        text: 'Content and collaborative scores are fused with a weighted combination tuned against a held-out validation set. The weights balance exploration (content) vs personalization (collaborative).',
      },
      {
        title: 'Flask API + Containerization',
        text: 'The recommender is served via a Flask API, containerized with Docker. A multi-stage Dockerfile minimizes image size for efficient Kubernetes pod spin-up.',
      },
      {
        title: 'Jenkins + ArgoCD CI/CD',
        text: 'Jenkins runs unit tests and builds Docker images on every commit. ArgoCD watches the Helm chart repository and auto-syncs Kubernetes deployments — full GitOps.',
      },
    ],
    results: [
      'Hybrid approach outperforms either content-based or collaborative filtering alone on NDCG@10',
      'Full GitOps pipeline: code push to production deployment in under 5 minutes',
      'Kubernetes deployment with auto-scaling handles traffic spikes without manual intervention',
      'Model versioning via DVC ensures reproducible recommendation behavior',
    ],
    highlights: [
      'Hybrid recommender: content-based + collaborative filtering fusion',
      'Full MLOps pipeline: Docker → Kubernetes → GitOps via ArgoCD',
      'Jenkins CI/CD with automated test and build stages',
      'Flask API optimized for low-latency recommendation serving',
      'DVC for model versioning and experiment tracking',
    ],
    techStack: [
      { label: 'ML', items: ['Collaborative Filtering', 'TF-IDF', 'Matrix Factorization'] },
      { label: 'Serving', items: ['Flask', 'Docker', 'Kubernetes'] },
      { label: 'CI/CD', items: ['Jenkins', 'ArgoCD', 'GitOps'] },
      { label: 'Tracking', items: ['DVC', 'Python'] },
    ],
  },
];
